### ISSUE TITLE
Website Typo

### ISSUE THREAD

**Issue by MaiAsagi** [safing/web#158]
![Quad9 Typo](https://user-images.githubusercontent.com/88003732/127063422-e221f738-efcd-452d-bc31-d3b219e030bd.jpg)

Suggested Changes

> Quad9 is a public DNS service that provides malware protection and is run a non-profit.

to

> Quad9 is a public DNS service that provides malware protection and is run by a non-profit.

**Comment by LukeSeers** [comment]
Thanks for the help! It should be updated and fixed on the website now :)
