### ISSUE TITLE
[Question] Can i create a Pull Request for you?

### ISSUE THREAD

**Issue by philippklemmer** [safing/web#16]
I want to contribute to the website. I do have 3 PR's for you, but i don't have the rights to add a pull request for you guys. Would it be possible to give me access?

**Comment by dhaavi** [comment]
Hey @philippklemmer, thank you for your contributions!

The responsible team will get back to you on Monday or Tuesday. (We have some exciting things coming up for the website!)

**Comment by philippklemmer** [comment]
Thank you! If i could contribute or help you with that, feel free to contact me :)

**Comment by davegson** [comment]
Thank you for your contributions! I'll review them tomorrow. Also, gonna PM you on twitter ;) Cheers
