### ISSUE TITLE
Comparison Blog Posts which show the PROS and CONS compared to other privacy protections

### ISSUE THREAD

**Issue by deroverda** [safing/web#160]
Hi, 

Great initiative, brilliant software. I haven't yet tried it out but I would really want to know the pros and cons comparing portmaster to simplewall, nextdns (or other dns providers) or a hardened firefox with ublock etc. 

Currently I'm using simplewall which sends an instant notification once an app is opened that requires internet connection. It's lightweight and does its job. Why would I also use portmaster? Or is portmaster meant to replace DNS-providers and software such as simplewall? I'm confused. Looking forward to your replies.

**Comment by davegson** [comment]
Hey there, thanks for the great input! We definitely agree, comparison blog posts would be helpful. We just recently got together and planned some of these, so a few should come out this year. You can easily subscribe to [the rss feed](https://safing.io/blog/) to grab them when they are published.

To get a better grasp for now, here is a short overview:

NextDNS blocks trackers and ads at the DNS Server, so you will query NextDNS for a domain and they will block domains as defined. **NextDNS supports all platforms and can also be set up network wide.** It however delegates trust to NextDNS, who you will have to trust with all your information.

A browser extension such as uBlock Origin also blocks trackers and malware, but will prevent your browser from doing that even before a DNS request goes out. **A browser extension blocks only within the browser, but more granular**, like you can visit a website but block its JavaScript.

Portmaster blocks trackers and malware on your whole device, not just on your browser. It cannot differentiate between content type like the extension, so we still _highly_ recommend you use uBlock Origin!

With Portmaster, you can configure settings for each app, so you can allow iE google.com for your browser but block it everywhere else. Portmaster can also block by connection type, like blocking all p2p/incoming/LAN connections system-wide, and then add exceptions where needed. And then it adds a few standard privacy protections by default, such as enabling encrypted DNS over TLS by default as well as activating filter lists to block malware, trackers, etc...

**Portmaster protects your device, not your network**. It does this locally, everywhere you go, Portmaster comes with you. So you can take it with you to a public WiFi.

Anyway, pitch over haha - if you have more questions let me know.

**Comment by LukeSeers** [comment]
I thought I would highlight one of the problems SimpleWall has in my opinion.

SimpleWall is a nifty bit of kit which handles app connections, but it doesn't handle any connections from the system level.

Since SimpleWall uses the Windows Filtering Platform (WFP) this opens the ability of Microsoft potentially bypassing their own system thus bypassing SimpleWall. In many respects your putting trust in Microsoft to not give out special permissions that bypass the system for whoever they think is best fit.

Portmaster forces all system-wide connections from kernel level through it's network monitoring system. If you do choses to try the Portmaster. You'll most likely see some weird windows apps that have been trying to make connections, but you probably wouldn't have seen them through SimpleWall.

**Comment by deroverda** [comment]
Thank you both for your thorough replies/explanations. I'm currently testing the software right now without any issues. 
I checked the taskmanager and noticed that there are many portmaster processes running in the background. Is this normal?

[Here's ](https://imgur.com/a/3cwyN47)how it looks like. All exe files point to the same .exe which is located here: "C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-2.exe".

**Comment by LukeSeers** [comment]
That's normal :)

**Comment by deroverda** [comment]
Thanks for the quick reply. You guys can close this "issue". Have a good one!
