### ISSUE TITLE
Overall accessibility and performances

### ISSUE THREAD

**Issue by narduin** [safing/web#178]
# Hello!

While testing portmaster and spn (great stuff) I noticed some issues regarding safing.io website.
I took the liberty of doing a small "audit" in order to report my findings here if you're interested.

This is definitely not complete but may be a good starting point.
I tried to link references to why I reported these as "issues". Feel free to ask/disagree about anyhing I said :)

**Let me know if/how I can help!**

## HTML
- [ ] mising `<h1>` in all pages (except blog)
- [ ] [`<button>` element](https://www.buttoncheatsheet.com/) used inside `<a>` tag
- [ ] newsletter subscription input [has no label](https://www.sarasoueidan.com/blog/accessible-text-labels/)

## ACCESSIBILITY
- [ ] no [focus styles](https://www.sarasoueidan.com/blog/focus-indicators/), keyboard nav is hard
- [ ] mobile menu toggle (checkbox) has no [label](https://www.sarasoueidan.com/blog/accessible-text-labels/)/text description
- [ ] no [skip to content link](https://css-tricks.com/how-to-create-a-skip-to-content-link/)

### global
- [ ] use `width` and `height` attributes on images [to avoid layout shifts](https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/)
- [ ] [offer `.webp`](https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli) images with `picture` element
- [ ] [optimize](https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli) existing jpg/png size
- [ ] [use videos](https://bitsofco.de/optimising-gifs/) or [animated](https://www.cassie.codes/posts/creating-my-logo-animation/) [svgs](https://css-tricks.com/animating-svg-css/) instead of gifs
- [ ] [lazy load](https://caniuse.com/loading-lazy-attr) images
- [ ] [avoid resizing images on the browser side](https://css-tricks.com/a-guide-to-the-responsive-images-syntax-in-html/)

### homepage
- [ ] intro gif is 10MB
- [x] safing profile image is 404

### SPN page
- [ ] layers.gif is 15MB, switch to static image
- [ ] switch.gif is 21MB, switch to static image
- [ ] video poster is 1.3MB displayed at a maximum of 659x369 while being 2880x1610

## CSS
- [ ] no fallback font specified, serif font is displayed while Roboto is loading
- [ ] [`font-display`](https://css-tricks.com/font-display-masses/) property not used
- [ ] `id` [used for styling](https://css-tricks.com/almanac/selectors/i/id/)
- [ ] [is full tailwind loaded?](https://tailwindcss.com/docs/optimizing-for-production)

**Comment by davegson** [comment]
Hey Nico,

thank you for using and testing both the Portmaster and SPN! And thank you for your website audit!

Your raised points are all valid and I am happy to see this as a starting point to further progress the website. Like all projects, iteration is key and with time, we will see where we evolve from here :)

### HTML

In terms of the HTML, we are currently rebuilding all of it to hide away most of the tailwind and instead use our custom tailwind components. You might have read about it in [the latest progress update](https://safing.io/blog/2021/12/07/progress-update-november/#tablecard-in_progress-6), and can also look at the ongoing progress / results over [on this Pull Request](https://github.com/safing/web/pull/177).

Therefore, I would wait with fixing elements within the HTML until the big refactor has completed or at least has gone far enough so we can work from the new branch. This probably applies to many of points you raised.

However, I will definitely keep this issue open and we will take the steps as the status allows us. I made all the points to check lists so we can keep track of things.

### First Step: Media Optimization

For now, I think the easiest thing to tackle are the media optimizations you suggested. Like resizing/optimizing/changing format of pictures.

Is it possible for you to run the website locally? Would you be able to optimize the existing image sizes or to convert them to `.webp`? And should we replace all `.pngs` to `.webp`? Or is `.webp` not supported everywhere yet?

If you are able, I would greatly appreciate a pull request. Feel free to discuss anything and everything with me. I just might be a bit slower to respond in the next couple of days, taking some days off here and there.

Thanks again for everything - so cool to see!

**Comment by narduin** [comment]
Hi!

That's great, can't wait to see the new version :)

I tried to run the website locally but I ran into this error:

```sh
➜ docker-compose up
Starting web_jekyll_1 ... done
Attaching to web_jekyll_1
jekyll_1  | ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
jekyll_1  | /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/spec_set.rb:90:in `block in materialize': Could not find jekyll-4.1.1 in any of the sources (Bundler::GemNotFound)
jekyll_1  | 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/spec_set.rb:85:in `map!'
jekyll_1  | 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/spec_set.rb:85:in `materialize'
jekyll_1  | 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/definition.rb:244:in `specs_for'
jekyll_1  | 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler/runtime.rb:18:in `setup'
jekyll_1  | 	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.24/lib/bundler.rb:149:in `setup'
jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.0/exe/jekyll:11:in `<top (required)>'
jekyll_1  | 	from /usr/gem/bin/jekyll:23:in `load'
jekyll_1  | 	from /usr/gem/bin/jekyll:23:in `<main>'
web_jekyll_1 exited with code 1
```

I'm not used to docker and jekyll so I don't realy know how to debug this…
I'll keep trying and see what I can do to optimize images and videos.

Happy holidays!

**Comment by narduin** [comment]
Hi!

I created a [fork and a branch](https://github.com/narduin/web/tree/optimization) where I optimized all static assets I could find.

I checked that all assets were correctly displayed and did not see anything missing but you might want to double check.
I replaced gif with videos and added `loading=lazy` to all images.
The size of the homepage was divided by 10 on initial load 🚀

**Comment by davegson** [comment]
Thanks so much @narduin!

Could you open a Pull Request for it?

You can do that via your fork:

- go to Pull Requests
- New Pull Request
- you will be at a place where you compare changes and nothing will be selected
- on the right side of the branches select the `optimization` branch for `narduin/web`
- you should end up at [this link](https://github.com/safing/web/compare/master...narduin:optimization)

Just want to make sure everyone sees you're the author ;)

Will have a look at this next week. Also, we have come pretty far with the HTML rework, you can check that out on this branch https://github.com/safing/web/tree/feature/integrate-safingTailwind - can also have a local spin if you like

I would not continue with other improvements until both your new branch and the tailwind one are merged - otherwise the conflicts might become too big of a mess

Thanks again!

**Comment by narduin** [comment]
Sorry about the delay, I missed your reply.

**Comment by davegson** [comment]
Hi @narduin,

after too long a delay, I am closing this as outdated - the website has evolved since.

Sorry that I let your efforts become tumbleweed. You would have deserved better!
