### ISSUE TITLE
Automate Monero payments

### ISSUE THREAD

**Issue by pluja** [safing/web#236]
**What would you like to add or change?**:

I would like to be able to pay with Monero and get automated confirmations of payments.

**Why do you and others need this?**:

 I don't want to be waiting for days to a manual confirmation of the payment since this does not make much sense.

Instead, some automated payment processor such as BTCPayServer (which works for Bitcoin, Monero, Litecoin, etc.). 

> See https://allark.io for an example of how BTCPayServer looks, just click “buy” on anything and see the interface. Currencies can be selected from the payment page.

Also, any other payment gateway listed in https://www.getmonero.org/resources/tools/.  The advantage of using BTCPayServer is that it is self-hosted, so 0 fees are applied.

**Comment by dhaavi** [comment]
We actually have auto-completion for Monero - but we don't show the confirmations yet. Can you check the status again?

**Comment by pluja** [comment]
Checked. It worked. There is a message saying that it needs manual approving. Maybe you should edit that! Thank you:)

**Comment by dhaavi** [comment]
Great!

Yes, we have recently improved that message, but it's not yet in production.
