### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by ethical-haquer** [safing/web#252]
**What is the bug / inaccuracy?**:
"Portmaster is easy privacy and pice of mind"
"The Plus Plan is meant for people who are curios about what is going on on their devices."

**What would you expect instead?**:
Should read:
"Portmaster is easy privacy and _peace_ of mind"
"The Plus Plan is meant for people who are _curious_ about what is going on on their devices."

**Comment by Raphty** [comment]
Thanks, the second one no one else found yet... The pice got called out multiple times but the curios not... thanks!!

**Comment by ethical-haquer** [comment]
No problem! :smiley:
