### ISSUE TITLE
Plus pricing incongruent

### ISSUE THREAD

**Issue by h4ckerle** [safing/web#254]
**What is the bug / inaccuracy?**:

Under https://safing.io/pricing/ the Plus Pricing is displayed as 4€/Month (billed anually when having it set to show per Month pricing. This is incongruent with the pricing for plus shown, having it set to Per Year pricing where it is shown as 40€/Year. 
![image](https://github.com/safing/web/assets/76652420/6b231b03-22a3-4078-92de-952b8db6bc02)
![image](https://github.com/safing/web/assets/76652420/19c06aaa-3263-48f7-a62d-8e765bcbd71a)

**What would you expect instead?**:
It seems that only yearly billing is possible for the plus plan therefore it should be shown as the correct 3,33€/Month billed anually.

**Comment by Raphty** [comment]
thanks for pointing this out, you are of course 100% correct, but we think it looks better that way, and it is a pleasant surprise when the year costs 40 instead of 48 euros
