### ISSUE TITLE
Update the SPN Repository url at the footer of the safing website.

### ISSUE THREAD

**Issue by D-I-J** [safing/web#257]
**What would you like to add or change?**:

update the SPN repository url in the footer of the website to the active repository.

**Why do you and others need this?**:

It introduces unnecessary clicks and you have to scroll to view the link to the active repository.

@dhaavi @vlabo @Raphty 
  consider assigning it to me.
I have done it.
I will create a pull request once you assign it to me.
please make a label for good first issue too.

**Comment by Raphty** [comment]
thank you  for the PR! I just merged it.
